---
- name: Install the MySQL packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - mysql-server-{{mysql_version}}
    - mysql-client-{{mysql_version}}
    - python-mysqldb
    - libmysqlclient-dev
    - python-pip
    - python-dev

- name: Sets the root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  ignore_errors: true

- name: Copy the root credentials as .mysql.cnf file
  template: src=mysql_root.cnf.j2 dest=~/.mysql.cnf mode=0600
